version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: ./compose/development/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - ./src:/src
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - dev-tinyblog-data:/var/lib/postgresql/data/
    restart: always

volumes:
  dev-tinyblog-data: