version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: tinyblog-api
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file:
      - .env.api
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    env_file:
      - .env.db
    volumes:
      - tinyblog-data:/var/lib/postgresql/data/
    restart: always

volumes:
  tinyblog-data: